// SPDX-License-Identifier: MIT

package types

import (
	"context"
)

// Runtime represents the standard set of methods for managing containers using different container runtimes.
type Runtime interface {
	SystemOps
	ContainerOps
	ImageOps
	EventOps
	TelemetryOps
}

// SystemOps represents a set of methods for managing the host container runtime.
type SystemOps interface {
	// Info returns a InfoResult with information about the host container runtime.
	Info(ctx context.Context) (InfoResult, error)

	// Login authenticates a user to a specified container registry.
	// If no ServerAddress is specified, docker.io registry will be used.
	Login(ctx context.Context, auth AuthConfig) error

	// Close terminates the connection to the runtime.
	Close() error
}

// ContainerOps represents a set of methods for managing containers on the host.
type ContainerOps interface {
	// ContainerCreate initializes a new container based on the provided ContainerCreateConfig.
	// It returns the ID of the created container.
	//
	// ContainerCreateConfig is a mandatory argument.
	ContainerCreate(ctx context.Context, cfg *ContainerCreateConfig) (ContainerCreateResult, error)

	// ContainerStart initializes and starts an existing container with the provided ID.
	// If the container is already running, no error is returned.
	ContainerStart(ctx context.Context, id string, opts *ContainerStartOptions) error

	// ContainerStop gracefully halts a running container with the provided ID.
	// If the container is already stopped, no error is returned.
	ContainerStop(ctx context.Context, id string, opts *ContainerStopOptions) error

	// ContainerPause pauses the container with the provided ID.
	// If the container is already paused, no error is returned.
	ContainerPause(ctx context.Context, id string, opts *ContainerPauseOptions) error

	// ContainerUnpause unpauses a previously paused container with the provided ID.
	// If the container was not paused before calling the function, an error is returned.
	ContainerUnpause(ctx context.Context, id string, opts *ContainerUnpauseOptions) error

	// ContainerRestart restarts the container with the provided ID.
	// If the container was not running before calling the function, it gets started.
	ContainerRestart(ctx context.Context, id string, opts *ContainerRestartOptions) error

	// ContainerRemove forcefully kills and removes a container with the provided ID.
	// If the container is not running, it is only removed.
	ContainerRemove(ctx context.Context, id string, opts *ContainerRemoveOptions) error

	// ContainerStatus returns a ContainerStatusResult of a container with the provided ID.
	ContainerStatus(ctx context.Context, id string, opts *ContainerStatusOptions) (ContainerStatusResult, error)

	// ContainerList returns a ContainerListResult documenting basic information about all containers
	// on the host system.
	ContainerList(ctx context.Context, opts *ContainerListOptions) (ContainerListResult, error)

	// ContainerWait waits for a container with the provided ID to finish its task and returns
	// the exit code from the task.
	//
	// ContainerWaitOptions is a mandatory argument.
	ContainerWait(ctx context.Context, id string, opts *ContainerWaitOptions) (ContainerWaitResult, error)

	// ContainerExec executes a given command inside the container with the provided ID and returns
	// the exit code and optionally contents of Stdout and Stderr.
	//
	// ContainerExecOptions is a mandatory argument.
	ContainerExec(ctx context.Context, id string, opts *ContainerExecOptions) (ContainerExecResult, error)

	// ContainerLogs returns a ContainerLogsResult containing a stream of logs generated by the container.
	//
	// ContainerLogsOptions is a mandatory argument.
	ContainerLogs(ctx context.Context, id string, opts *ContainerLogsOptions) (ContainerLogsResult, error)
}

// ImageOps represents a set of methods for managing images on the host.
type ImageOps interface {
	// ImagePull pulls an image from a container registry.
	// If the image name does not contain a registry address, docker.io registry is used.
	//
	// If the Progress channel in ImagePullOptions exists, the operation will populate it with
	// ImagePullProgress messages containing information about the progress.
	// If the channel is nil, the function will return after the image has been pulled.
	ImagePull(ctx context.Context, name string, opts *ImagePullOptions) error

	// ImageInspect returns an ImageInspectResult containing information about an image with the provided ID.
	ImageInspect(ctx context.Context, id string, opts *ImageInspectOptions) (ImageInspectResult, error)

	// ImageList returns a list of ImageSummary documenting basic information about all images on the host system.
	ImageList(ctx context.Context, opts *ImageListOptions) (ImageListResult, error)

	// ImageRemove removes an image with the provided ID from the host system and returns
	// information about all removed tags corresponding with the provided image ID.
	ImageRemove(ctx context.Context, id string, opts *ImageRemoveOptions) (ImageRemoveResult, error)

	// ImagePrune requests the host container runtime to remove unused data and returns
	// information about pruned images and reclaimed space.
	ImagePrune(ctx context.Context, opts *ImagePruneOptions) (ImagePruneResult, error)
}

// EventOps represents a set of methods for monitoring events from containers on the host.
type EventOps interface {
	// EventsStream returns an EventsStreamResult containing channels for events and errors on the
	// host system.
	EventsStream(ctx context.Context, opts *EventsStreamOptions) EventsStreamResult
}

// TelemetryOps represents a set of methods for obtaining telemetry data from the container runtime.
type TelemetryOps interface {
	// ContainerStats returns a ContainerStatsResult containing information about resources used by
	// the container with the provided ID.
	ContainerStats(ctx context.Context, id string, opts *ContainerStatsOptions) (ContainerStatsResult, error)
}
